apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret-file
  namespace: default
type: Opaque
data:
  secret.file: |
    Y2F0IDw8RU9GIHwgc3VkbyB0ZWUgL2V0Yy9tb2R1bGVzLWxvYWQuZC9rOHMuY29uZgpvdmVybGF5CmJyX25ldGZpbHRlcgpFT0YKCnN1ZG8gbW9kcHJvYmUgb3ZlcmxheQpzdWRvIG1vZHByb2JlIGJyX25ldGZpbHRlcgoKIyBzeXNjdGwgcGFyYW1zIHJlcXVpcmVkIGJ5IHNldHVwLCBwYXJhbXMgcGVyc2lzdCBhY3Jvc3MgcmVib290cwpjYXQgPDxFT0YgfCBzdWRvIHRlZSAvZXRjL3N5c2N0bC5kL2s4cy5jb25mCm5ldC5icmlkZ2UuYnJpZGdlLW5mLWNhbGwtaXB0YWJsZXMgID0gMQpuZXQuYnJpZGdlLmJyaWRnZS1uZi1jYWxsLWlwNnRhYmxlcyA9IDEKbmV0LmlwdjQuaXBfZm9yd2FyZCAgICAgICAgICAgICAgICAgPSAxCkVPRgoKIyBBcHBseSBzeXNjdGwgcGFyYW1zIHdpdGhvdXQgcmVib290CnN1ZG8gc3lzY3RsIC0tc3lzdGVtCgpzdWRvIGFwdCB1cGRhdGUKc3VkbyBhcHQgaW5zdGFsbCBjb250YWluZXJkIC15CgpzdWRvIG1rZGlyIC1wIC9ldGMvY29udGFpbmVyZApjb250YWluZXJkIGNvbmZpZyBkZWZhdWx0IHwgc3VkbyB0ZWUgL2V0Yy9jb250YWluZXJkL2NvbmZpZy50b21sCnN1ZG8gc3lzdGVtY3RsIHJlc3RhcnQgY29udGFpbmVyZC5zZXJ2aWNlCnNlcnZpY2UgY29udGFpbmVyZCBzdGF0dXMK

